### ISSUE TITLE
wrong reference for moduleId in child-router.js

### ISSUE THREAD

**Issue by bzd2000** [SpoonX/aurelia-skeleton#1]
I think there is an error in the moduleId reference in the child-router.js 

It should be 'page/welcome' instead of 'welcome'.
The same for users and child-router.

Kr,
Filip.

**Comment by RWOverdijk** [comment]
@bzd2000 You're absolutely right. I'm actually working on a new skeleton. Unfortunately that causes this one to be neglected.

If you're willing to help out, I do accept pull requests.

**Comment by bzd2000** [comment]
What sort of skeleton are you going to make?
I'm looking for a skeleton which includes authentication + backend connectivity.
I probably go for loopback as back-end.

In fact the combination of your aurelia-auth and eventually your Aurelia-orm + loopback could be a good combination.

But I guess this is out of scope for your skeleton.

**Comment by RWOverdijk** [comment]
@bzd2000 It is, but I think I might write a tutorial on that :) You should join us on gitter, one of the devs there has a similar setup to yours. https://gitter.im/SpoonX/Dev

**Comment by bzd2000** [comment]
ok thx for the info.

Should I close this issue then?

**Comment by RWOverdijk** [comment]
Yeah that's fine :)
