### ISSUE TITLE
Typescript Version

### ISSUE THREAD

**Issue by coderabsolute** [SpoonX/aurelia-skeleton#6]
This skeleton is great but is it possible to get the TypeScript Version?

**Comment by RWOverdijk** [comment]
@coderabsolute The plan is there, but it's going to take time. Our swan-example is more extended. If you want you can make a start and help us out!

**Comment by coderabsolute** [comment]
@RWOverdijk: I would love to help you guys out but am not experienced enough to work on frontend. Am from C# background and this is my first project for frontend app.

**Comment by RWOverdijk** [comment]
@coderabsolute That makes sense. It'll be built eventually but unfortunately it'll take some time.

**Comment by coderabsolute** [comment]
@RWOverdijk Am looking at swan-example-client unfortunately this project is also not in TypeScript. Wondering, do you know any other template which supports the TypeScript and using aurelia-authentication?
